"""added new column in address

Revision ID: 4057e8868ce7
Revises: 6e9887b732ba
Create Date: 2023-05-16 11:32:45.027894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4057e8868ce7'
down_revision = '6e9887b732ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('std_code', sa.Integer(), nullable=True))

    # Changing upgrade according to required.
    op.execute('UPDATE address SET std_code = pin_code%10000')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('std_code')

    # ### end Alembic commands ###
